[package]
name = "detective-board"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
serde = "1.0.217"
serde_json = "1.0.138"
surrealdb = "2.2.0"
tokio = { version = "1.43.0", features = ["full"] }
